CREATE TABLE LEAGUE_OF_LEGENDS_CHAMPIONS
(
    VERSION                    VARCHAR2(100 BYTE),
    LANGUAGE                   VARCHAR2(100 BYTE),
    ID                         VARCHAR2(100 BYTE),
    KEY                        VARCHAR2(100 BYTE),
    NAME                       VARCHAR2(100 BYTE),
    TITLE                      VARCHAR2(100 BYTE),
    BLURB                      VARCHAR2(4000 BYTE),
    INFO_ATTACK                NUMBER,
    INFO_DEFENSE               NUMBER,
    INFO_MAGIC                 NUMBER,
    INFO_DIFFICULTY            NUMBER,
    IMAGE_FULL                 VARCHAR2(100 BYTE),
    IMAGE_SPRITE               VARCHAR2(100 BYTE),
    IMAGE_GROUP                VARCHAR2(100 BYTE),
    IMAGE_X                    NUMBER,
    IMAGE_Y                    NUMBER,
    IMAGE_W                    NUMBER,
    IMAGE_H                    NUMBER,
    TAGS                       VARCHAR2(100 BYTE),
    PARTYPE                    VARCHAR2(100 BYTE),
    STATS_HP                   NUMBER,
    STATS_HPPERLEVEL           NUMBER,
    STATS_MP                   NUMBER,
    STATS_MPPERLEVEL           NUMBER,
    STATS_MOVESPEED            NUMBER,
    STATS_ARMOR                NUMBER,
    STATS_ARMORPERLEVEL        NUMBER,
    STATS_SPELLBLOCK           NUMBER,
    STATS_SPELLBLOCKPERLEVEL   NUMBER,
    STATS_ATTACKRANGE          NUMBER,
    STATS_HPREGEN              NUMBER,
    STATS_HPREGENPERLEVEL      NUMBER,
    STATS_MPREGEN              NUMBER,
    STATS_MPREGENPERLEVEL      NUMBER,
    STATS_CRIT                 NUMBER,
    STATS_CRITPERLEVEL         NUMBER,
    STATS_ATTACKDAMAGE         NUMBER,
    STATS_ATTACKDAMAGEPERLEVEL NUMBER,
    STATS_ATTACKSPEEDPERLEVEL  NUMBER,
    STATS_ATTACKSPEED          NUMBER,

    CONSTRAINT PK_LEAGUE_OF_LEGENDS_CHAMPIONS PRIMARY KEY (VERSION, LANGUAGE, ID)
);